# Gradle
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4G"
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.caching=true
# Android
android.enableJetifier=true
android.useAndroidX=true
# Kapt
kapt.incremental.apt=false
kapt.use.worker.api=false
# JB
org.jetbrains.compose.ios.resources.sync=false
# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.mpp.androidSourceSetLayoutVersion=2
# Tests
testTask.ignoreFailures=false
# Custom - Android
makeevrserg.android.sdk.compile=36
makeevrserg.android.sdk.min=23
makeevrserg.android.sdk.target=36
# Custom - java
makeevrserg.java.ktarget=17
makeevrserg.java.source=11
makeevrserg.java.target=17
# Custom - Project
makeevrserg.project.description=Template for KMP applcation
makeevrserg.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
makeevrserg.project.group=com.makeevrserg.applicationtemplate
makeevrserg.project.name=ApplicationTemplate
makeevrserg.project.url=https://github.com/makeevrserg/KMP-Template
makeevrserg.project.version.code=37
makeevrserg.project.version.string=1.5.0