name: Build Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  validate_gradle_wrapper:
    name: "Gradle Wrapper"
    uses: ./.github/workflows/call-gradle-wrapper-validation.yml
  build_release_artifacts:
    name: "Release Artifacts"
    needs: [ validate_gradle_wrapper ]
    uses: ./.github/workflows/call-upload-artifacts.yml
    secrets:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  publish_github_release:
    name: "GitHub Release"
    needs: [ validate_gradle_wrapper, build_release_artifacts ]
    permissions:
      contents: write
    uses: ./.github/workflows/call-upload-github-release.yml
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
