name: CI
on:
  push:
    branches:
      - test
jobs:
  gradle_validation:
    uses: ./.github/workflows/gradle-wrapper-validation.yml
  create_artifact:
    needs: [ gradle_validation ]
    uses: ./.github/workflows/create-artifacts.yml
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
