name: "Create artifacts"
on:
  workflow_call:
    secrets:
      ACTIONS_TOKEN:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true
      STORE_PASSWORD:
        required: true
      KEYSTORE_BASE64:
        required: true
jobs:
  publish:
    name: Upload artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: "android"
            task: ":instances:androidApp:assembleRelease"
            artifacts_path: "./instances/androidApp/build/outputs/apk/release"
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'makeevrserg.project.name makeevrserg.project.version.string'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Build with Gradle ${{ matrix.id }}
        uses: gradle/gradle-build-action@v3
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        with:
          arguments: ${{ matrix.task }} --stacktrace
      - uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        name: "Upload ${{ matrix.id }}"
        with:
          name: ${{ matrix.id }}
          path: ${{ matrix.artifacts_path }}