name: "Check version changed"
on:
  workflow_call:
    inputs:
      ASSERT:
        required: false
        type: boolean
        default: false
    outputs:
      IS_SAME_VERSIONS:
        description: "The name of requested build variant"
        value: ${{ jobs.compare_versions.outputs.IS_SAME_VERSIONS }}

jobs:
  #  ${{ jobs.get_version_from_target_branch.outputs.TARGET_VERSION }}
  get_version_from_target_branch:
    name: Get version from target branch
    runs-on: ubuntu-latest
    outputs:
      TARGET_VERSION: ${{ steps.properties.outputs.makeevrserg-project-version-string }}
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      #  ${{ steps.properties.outputs.makeevrserg-project-version-string }}
      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'makeevrserg.project.name makeevrserg.project.version.string'

  #  ${{ jobs.get_version_from_current_branch.outputs.CURRENT_VERSION }}
  get_version_from_current_branch:
    name: Get version from current branch
    runs-on: ubuntu-latest
    outputs:
      CURRENT_VERSION: ${{ steps.properties.outputs.makeevrserg-project-version-string }}
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4

      #  ${{ steps.properties.outputs.makeevrserg-project-version-string }}
      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './gradle.properties'
          properties: 'makeevrserg.project.name makeevrserg.project.version.string'

  # ${{ jobs.compare_versions.outputs.IS_SAME_VERSIONS }}
  compare_versions:
    needs: [ get_version_from_current_branch, get_version_from_target_branch ]
    name: "Compare versions ${{ needs.get_version_from_target_branch.outputs.TARGET_VERSION }} and ${{ needs.get_version_from_current_branch.outputs.CURRENT_VERSION }}"
    runs-on: ubuntu-latest
    outputs:
      IS_SAME_VERSIONS: ${{ needs.get_version_from_target_branch.outputs.TARGET_VERSION }} == ${{ needs.get_version_from_current_branch.outputs.CURRENT_VERSION }}
    steps:
      # steps.create_baseline_task.outputs.BASELINE_TASK
      - id: print
        run: |
          echo "${{ needs.get_version_from_target_branch.outputs.TARGET_VERSION }}"
          echo "${{ needs.get_version_from_current_branch.outputs.TARGET_VERSION }}"

      - name: Failed if versions is same
        if: ${{ inputs.ASSERT }} == true
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: core.setFailed('Version makeevrserg.project.version.string at gradle.properties has not changed!')