name: Check Develop
on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'develop'
      - 'master'
jobs:
  gradle_validation:
    name: Validate gradle wrapper
    uses: ./.github/workflows/gradle-wrapper-validation.yml
  detekt_validation:
    name: Check by detekt
    needs: gradle_validation
    uses: ./.github/workflows/detekt-validation.yml
  tests_validation:
    name: Run Unit tests
    needs: detekt_validation
    uses: ./.github/workflows/tests-validation.yml